[package]
name = "tinyren"
version = "0.1.0"
edition = "2021"

[lib]
name = "tinyren"
path = "src/lib.rs"

[[bin]]
name = "threelines"
path = "src/threelines.rs"

[[bin]]
name = "wireframe"
path = "src/wireframe.rs"

[profile.release]
debug = 1
